import Head from "next/head";
import { useEffect, useState } from "react";
import { Coins, Favorites } from "../components";
import { useUser } from "@auth0/nextjs-auth0/client";
export default function Home() {
  const [favorites, setFavorites] = useState([]);
  const [favCoin, setFavCoin] = useState([]);
  const { user } = useUser();

  useEffect(() => {
    if (favorites.length > 0) {
      localStorage.setItem("favorites", JSON.stringify(favorites));
    }
    const favorite = JSON.parse(localStorage.getItem("favorites"));
    if (favorite) {
      setFavCoin(favorite);
    }
  }, [favorites]);
  const onAdd = (coin) => {
    setFavorites([...favorites, coin]);
  };
  return (
    <div>
      <Head>
        <title>Crypto X-Change</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main className="relative flex">
        {user && (
          <aside className="border rounded shadow-2xl w-72 h-64 ml-8 px-4 ">
            <h4 className="text-center">Followed Coins</h4>
            <Favorites props={favCoin} />
          </aside>
        )}
        <Coins onAdd={onAdd} />
      </main>
    </div>
  );
}
