import Head from "next/head";
import { Coins } from "../components";

export default function Home({ coinsList }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-3xl text-center font-bold underline my-12">
          Crypto X-Change!
        </h1>
        <Coins coinsList={coinsList} />
      </main>
    </div>
  );
}
export async function getServerSideProps() {
  const res = await fetch(
    "https://api.coingecko.com/api/v3/coins/markets?vs_currency=eur&order=market_cap_desc&per_page=10&page=1&sparkline=false"
  );
  const coinsList = await res.json();

  return {
    props: { coinsList },
  };
}
